### ISSUE TITLE
Failed to download all specified files. Exiting. Error Message: Unable to connect to the remote server.

### ISSUE THREAD

**Issue by andresravinet** [rkuehfus/AzureMonitoringHackathon#2]
Hey Robert,
I'm receiving the following error when the script tries to provision the VMSS:
Failed to restart virtual machine scale set 'arwebScaleSet'. Error: VM has reported a failure when processing extension 'CustomScriptExtension'. Error message: "Failed to download all specified files. Exiting. Error Message: Unable to connect to the remote server".

Also, here is the exact text of the VMSS CustomScriptExtension:
{
  "fileUris": [
    "https://raw.githubusercontent.com/rkuehfus/AzureMonitoringHackathon/master/SetupWebServers.ps1"
  ],
  "commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File SetupWebServers.ps1 arVSSrv17 vmadmin *********"
}

**Comment by rkuehfus** [comment]
Thanks for the heads up.  I know it just deployed successfully a few days ago but that doesn't mean there wasn't a recent changes to one of my dependencies that is causing a issue.  I will have a look.

**Comment by rkuehfus** [comment]
This is fixed.  I had to update the version of dotnet core as the eShopOnWeb site I use was updated.  Delete your scaleset and redeploy your template.  No need to delete everything.
