### ISSUE TITLE
Step by Step guide

### ISSUE THREAD

**Issue by iamthewall** [rkuehfus/AzureMonitoringHackathon#3]
Hi rkuehfus. 

I know this could be so much to ask for but it would be nice to have an step by step guide of how to deploy the entire hackathon so customer with less level on azure can use it. Hope you have something like that in the future. 

Thanks for this amazing contribution.

**Comment by rkuehfus** [comment]
I have a setup guide published with a link in the main page.  Check it out.  I also have a proctors guide in the works.  Thanks for the feedback and keep it coming.

**Comment by rkuehfus** [comment]
There is a link to the proctors guide from the main page.  Over 80 pages of fun. Enjoy.
